os: osx
sudo: required
language: python
python:
   - "3.6"

before_install:
      - brew install libgit2
      - pip install -r requirements.txt

script:
      - export builder=$builder
      - python ./manage.py test
