os: osx
sudo: required
language: generic

before_install:
      - brew install python3
      - brew install libgit2
      - virtualenv venv -p python3
      - source venv/bin/activate
      - pip install -r requirements.txt

script:
      - export builder=$builder
      - python ./manage.py test
