os: osx
sudo: required
language: generic

before_install:
      - pyenv install 3.6.1
      - pyenv global 3.6.1
      - brew install libgit2
      - pip install -r requirements.txt

script:
      - export builder=$builder
      - python ./manage.py test
